name: Synthetic 404 Monitoring

on:
  schedule:
    - cron: '0 9 * * *'  
  workflow_dispatch:     

jobs:
  check-404-endpoint:
    runs-on: ubuntu-latest
    steps:
      - name: Check 404 page response
        run: |
          echo "Testing 404 endpoint..."
          STATUS=$(curl -s -o /dev/null -w "%{http_code}" )
          echo "Status code: $STATUS"
          if [ "$STATUS" -ne 404 ]; then
            echo "❌ Expected 404 but got $STATUS"
            exit 1
          fi
