name: OWASP ZAP Full Scan

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  zap_scan:
    runs-on: ubuntu-latest

    steps:
      - name: ZAP Full Scan
        uses: 
        with:
          target: 'https://github.com/RavishanPerera/404error.git'
